### ISSUE TITLE
Redeploy from staging or remove staging

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#121]
The main site is a couple weeks out-of-date. Can we redeploy from staging? Personally, I'd just get rid of staging as I'm not sure it's worth the overhead

**Comment by brittneypostma** [comment]
I agree, not sure that we need it and changes can be more easily pushed without it.

**Comment by kevmodrome** [comment]
I think we could definitely use some kind of GitHub action that runs every week or so that re-deploys the website. I'd like to keep the staging branch, it's a nice sanity check and stops us from bringing the site down 🙏 I don't have much experience writing GH actions though, I'll have to take a look during the week.

**Comment by brittneypostma** [comment]
An action would be nice, but I haven't used them either. Sounds like a plan though.

**Comment by MacFJA** [comment]
As it's now, the `staging` branch doesn't exist anymore.
Closing the issue
