### ISSUE TITLE
recipes: add a small one on a good PurgeCSS / Tailwind extractor for Svelte CSS classes

### ISSUE THREAD

**Issue by frederikhors** [svelte-society/sveltesociety.dev#203]
I opened https://github.com/sveltejs/kit/issues/891.

[Apparently](https://github.com/sveltejs/kit/issues/891#issuecomment-813478973) @babichjacob doesn't like it. 

Can we add a recipe for Tailwind here?

The problem with personal projects - like his own - is that sooner or later they vanish. A collection of recipes like yours has an official role and is maintained over time.

But apparently this concept is difficult to get across.

Sometimes it seems like a competition to see who closes the issue first.

**THE ISSUE I OPENED:**

> **Is your feature request related to a problem? Please describe.**
Given (from docs):

> SvelteKit does all the boring stuff for you so that you can get on with the creative part.

> and given a lot of people is using Tailwind (and the amazing [Tailwind JIT](https://github.com/tailwindlabs/tailwindcss-jit)) with [PurgeCSS](https://github.com/FullHuman/purgecss) but **there is no clear indication of what the right code is to extract the CSS Svelte classes**.

> **Describe the solution you'd like**
> Can we please add a note on docs for how to write a good CSS classes extractor for PurgeCSS?

> **Describe alternatives you've considered**
> I read a lot of pages like this: https://github.com/tailwindlabs/tailwindcss/discussions/1731.

**Comment by kevmodrome** [comment]
I don't think it has much to do with anyone liking it or not, It's just that it probably doesn't make sense to have it in the docs. It does make more sense here.

It's probably a good idea to have a recipe category that contains more in-depth information on how to integrate with other libraries and frameworks. The one downside to this is that I have a suspicion that it might get out of date pretty quickly. Anyway, we can always try. You're free to add one if you want make a recipe for this.

**Comment by benmccann** [comment]
I personally think that pointing to [svelte-add/tailwindcss](https://github.com/svelte-add/tailwindcss) is the best solution. My experience is that the setup has had to change frequently and it would quickly get out of date if we tried to put it on the site. Adders have some strong advantages over recipes such as having its own issue tracker, being able to automatically apply it with a command, and being able to add tests to ensure the setup is working. It's very well maintained, widely used, and the maintainer also has been helping on SvelteKit as well, so I view it as almost semi-official. If an adder were to become unmaintained I'm sure that someone from the community would create a competing one. There are many community adders already. I think that we could have a section for adders in the Boilerplates section where we can list all the community adders (https://github.com/svelte-society/sveltesociety.dev/issues/231). That section can show stars and last updated date in order to help people figure out which ones are better maintained, which would also be difficult with recipes
