### ISSUE TITLE
Svelte Component Index

### ISSUE THREAD

**Issue by antony** [svelte-society/sveltesociety.dev#5]
A lot like awesome-svelte, but more polished + manageable. We can start with awesome-svelte as a base perhaps.

- [x] A list of different component categories
- [ ] A screenshot of the component
- [ ] Author
- [ ] Github link
- [x] NPM/yarn Instructions

Proposal from https://github.com/sveltejs/svelte/issues/1070

**Comment by dhonx** [comment]
Is this just a website or just on an MD file?

**Comment by dhonx** [comment]
@antony I wanna participate with this one..

**Comment by kevmodrome** [comment]
Hi @dhonx this will one part of the website. If you want to participate you can read the #1, #2 and #4 to get started with understanding what the project is about. We also have a [Discord server](https://discord.gg/9fj32Tw) you can join.

**Comment by kevmodrome** [comment]
What other websites can we get inspired by when it comes to this?

- [Elm Packages](https://package.elm-lang.org/)
- [NPM](https://www.npmjs.com/search?q=Svelte)
- [Hex](https://hex.pm/packages)
- [Bit](https://bit.dev/components)

We need an index page that lists all the components as well as individual pages for each package. I'm personally a fan of a card-like view where you can see some kind of visual preview of the component or the code. This has some drawbacks of course, such as lower information density. But this is probably a question for the design issue rather than this one.

When it comes to individual pages I think that one huge feature would be to have the Svelte REPL right on each package page so that you can instantly play around with the package, without having to download it.

**Comment by antony** [comment]
The Svelte REPL isn't documented that well so it can be hard to integrate, but I think @pngwn has done it so perhaps he can provide some pointers.

**Comment by pngwn** [comment]
I know the REPL relatively well. I’ve used it as is but also forked it to edit the internals. I should write some basic documentation the REPL repo itself, just so people can get started. 

But if you want any pointers you know I’m always available. Or if you want me to take on that work I’d be happy to do so.

**Comment by antony** [comment]
@pngwn - I think either is fine. If you do document the process you are also closing a couple of issues (I can't find them now) about people wanting to know how to integrate a REPL on their own sites.

If you document it perhaps we could dogfood the docs by integrating it according to the instructions you provide.

**Comment by pngwn** [comment]
Sounds good!

**Comment by kevmodrome** [comment]
I've used @pngwn code form his bristalk to integrate the REPL in an upcoming site i'm building so i'm somewhat familiar at least with how to get it up and running but I don't know nearly enough to customize it or anything. Your help would be most welcome when the time comes. I'm thinking it can be a Phase 2 thing, rather than a Phase 1 thing.

I think a JSON file can work to begin with but the end goal (at least in my mind) is to stick it in the back-end so that we can handle things like user submissions, moderation, etc. in an easy to work with interface.

**Comment by ryanatkn** [comment]
Related to what @antony described, [here's how Ember Observer does things](https://emberobserver.com/about), including a simple automated scoring rubric to maintain a minimum quality bar.

**Comment by kevmodrome** [comment]
I like the idea of an automated score!

**Comment by TheComputerM** [comment]
I created a awesome svelte list: https://github.com/TheComputerM/awesome-svelte
Transform JSON to markdown for easy maintainability: https://github.com/TheComputerM/awesome-svelte/blob/master/index.js

**Comment by MacFJA** [comment]
What is the list of component category?
Currently there are only 3: `"ui"`, `"forms"` and _undefined_ (`""`)

The list I propose (still incomplete, lots of component don't fit any of these):
 - **Boilerplate** (Project template)
 - **Data Visualisation** (Grid, Table, Graph, etc.: Display dataset to users)
 - **Design Pattern** (Component to help solving a common design problem)
 - **Developer Experience** (Tooling, plugin to help during development, builder, etc.)
 - **Forms & User Input** (Component to collect data/user input, user input validation)
 - **Integration** (External library or service integration)
 - **Router** (Self explanatory)
 - **Store** (Self explanatory)
- **Design System** (Full UI lib, Bootstrap, Bulma, etc.)
- **Testing** (Unit test, Functional test, E2E test, etc.)

(Link to #88 )

**Comment by sw-yx** [comment]
LGTM

**Comment by sw-yx** [comment]
this was done by MacFJA :) #88

**Comment by swyxio** [comment]
i have been MIA for a while bc i moved countries 😅  will pick up soon when i settle in to my new place. keep going gang!!
